---
efiBootLoader: grub
kernelSearchPath: /usr/lib/modules
kernelPattern: "^vmlinuz.*"
kernelParams: [ quiet, splash ]
grubInstall: grub-install
grubMkconfig: grub-mkconfig
grubCfg: /boot/grub/grub.cfg
grubProbe: grub-probe
efiBootMgr: efibootmgr
efiBootloaderId: linxira
installEFIFallback: true
installHybridGRUB: false
