---
efi:
  mountPoint: /boot/efi
  recommendedSize: 1024MiB
  minimumSize: 512MiB
  label: EFI
userSwapChoices: [ none ]
initialPartitioningChoice: none
initialSwapChoice: none
defaultPartitionTableType: gpt
requiredPartitionTableType: gpt
defaultFileSystemType: btrfs
availableFileSystemTypes: [ btrfs ]
luksGeneration: luks2
allowManualPartitioning: false
enableLuksAutomatedPartitioning: false
lvm:
  enable: false
essentialMounts: [ "live-*", control, ventoy ]
requiredStorage: 24
