---
units:
  - name: NetworkManager.service
    action: enable
    mandatory: true
  - name: sddm.service
    action: enable
    mandatory: true
  - name: cronie.service
    action: enable
    mandatory: true
