---
defaultGroups:
  - users
  - audio
  - input
  - video
  - storage
  - wheel
sudoersGroup: wheel
sudoersConfigureWithGroup: true
setRootPassword: false
doAutologin: false
passwordRequirements:
  minLength: 8
  maxLength: 128
allowWeakPasswords: false
allowWeakPasswordsDefault: false
user:
  shell: /bin/bash
  forbidden_names: [ root, installer ]
  home_permissions: "o700"
hostname:
  location: EtcFile
  writeHostsFile: true
  template: "linxira-${cpu}"
  forbidden_names: [ localhost ]
allowActiveDirectory: false
