---
modules-search: [ local ]

instances:
  - id: validate
    module: linxiravalidate
  - id: components
    module: packagechooser
    config: packagechooser_components.conf
  - id: desktop
    module: packagechooser
    config: packagechooser_desktop.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - packagechooser@desktop
      - packagechooser@components
      - users
      - summary
  - exec:
      - partition
      - mount
      - linxirapacstrap
      - linxiraoptional
      - machineid
      - locale
      - keyboard
      - localecfg
      - fstab
      - initcpiocfg
      - linxirabranding
      - initcpio
      - users
      - displaymanager
      - hwclock
      - services-systemd
      - bootloader
      - linxiravalidate@validate
      - umount
  - show:
      - finished

branding: linxira
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
